pep_version: 2.1.0
sample_table: samples.csv
name: ctg
description: Prototype processing PEP for sequencing center
properties:
  samples:
    type: array
    items:
      type: object
      properties:
        project_id:
          type: string
          description: The serial number of the project given in the form YYYY_XXX
          pattern: ^\\d{4}_\\d{3}$
        sample_name:
          type: string
          description: The sample name A-Z,a-z, _ and - only! Pep specification index
            column. Don't change this name!
          pattern: ^[0-9A-Za-z_-]+$
        index:
          type: string
          description: The nucleotide sequence of the index
          pattern: ^[ATCG]+$
        index2:
          type: string
          description: The nucleotide sequence of the second index
          pattern: ^[ATCG]+$
      required:
      - project_id
      - sample_name
      - index
      - index2
required:
- samples

super_table: projects.csv
super_properties:
  projects:
    type: array
    items:
      type: object
      properties:
        project_id:
          type: string
          description: The serial number of the project given in the form YYYY_XXX
          pattern: ^\\d{4}_\\d{3}$
        bcl:
          type: string
          description: whether to deliver bcl files for this project, can only be
            yes or no
          pattern: ^YES|NO|[Yy]es|[Nn]o$
        fastq:
          type: string
          description: whether to deliver fastq files for this project, can only be
            yes or no
          default: true
          pattern: ^YES|NO|[Yy]es|[Nn]o$
        bam:
          type: string
          description: whether to deliver bam files for this project, can only be
            yes or no
          pattern: ^YES|NO|[Yy]es|[Nn]o$
        vcf:
          type: string
          description: whether to deliver vcf files for this project, can only be
            yes or no
          pattern: ^YES|NO|[Yy]es|[Nn]o$
        rna_counts:
          type: string
          description: whether to deliver raw rna counts for this project, can only
            be yes or no
          pattern: ^YES|NO|[Yy]es|[Nn]o$
        differential_expression:
          type: string
          description: whether to deliver diffexp results for this project, can only
            be yes or no
          pattern: ^YES|NO|[Yy]es|[Nn]o$
        fastqc:
          type: string
          description: whether to deliver fastqc reports for this project, can only
            be yes or no
          default: true
          pattern: ^YES|NO|[Yy]es|[Nn]o$
        fastqscreen:
          type: string
          description: whether to deliver fastqscreen reports for this project, can
            only be yes or no
          pattern: ^YES|NO|[Yy]es|[Nn]o$
      required: project_id
